name: Check the quality of my code
on:
  push:

jobs:
  quality_check:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
      - name: Run format
        working-directory: .\lib
        run: flutter format -l 120 --set-exit-if-changed .
      - name: Run analysis
        working-directory: .\
        run: flutter analyze